### ISSUE TITLE
units line

### ISSUE THREAD

**Issue by espencer78** [Chilldose/COMET#20]
When reading in a text file is it necessary to have a units line?  I tried commenting out the units line by putting a "#" in front of it in the yml file, but still got the error "Something went wrong while importing the file C:/Comet/CVIV/Comet_IV.txt with error: 'units_line'"

**Comment by Chilldose** [comment]
In the current version yes. Since a plot without units is a plot missing a key part. Furthermore, the plotting scripts have functions to automatically convert units in different orders of magnitude. For them to work it needs units.

But I changed it now that "units_line" is not a hard requirement anymore. But it will raise some warnings an errors. But it will plot. If you do not have units in your file, the best action would be to add it in the ASCII file description. Just add the key: value:: "units": ["unit1", "unit2", etc] so you can define units for your measurement in the config file. This also works for measurements with: "measurements": [....]. This will override all extracted units and measurements from the file.
