### ISSUE TITLE
Information from header for database

### ISSUE THREAD

**Issue by espencer78** [Chilldose/COMET#25]
Some way to extract information from the header of a measurement text file to be included in the xml file to be uploaded to the database.  Perhaps some keywords could be implemented so everyone would have to generate headers using these keywords:

#SensorName: <Sensor_Name)
#TestLocation: Brown
#StartTime: 05/11/2020 14:25
 
etc.

**Comment by Chilldose** [comment]
I think I have found suitable solution:

I have added now a first iteration of XML file generation for datafiles.

It uses a config file which must be present in the home directory of your config (same dir as the settings file).
In order to use this template you have to put the filename (without extension) as a settings parameter: 
'xml_template: MyTemplate'

To see an example how it works, please load the DataVisualization GUI, plot some of the testdata and choose save as xml.

**Comment by Chilldose** [comment]
And concerning how the script extracts values from your header file. In the config are under the Templates entry key value pairs. The key is the name of the entry in the final XML file and the value written in <..> is the base name of your entry. The script will search your header for the regex: <..>\W\s?(.*) and the value in the () will be inserted in the XML file. This should be a solution for most headers.
